version: '3.8'

services:
  app:
      container_name: app
      build: ./quiz-app/.
      ports:
        - "8080:8080"  # Adjust the port to match the port your application listens on
      restart: always
      networks:
        - intranet
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: quiz         # Database name
      POSTGRES_USER: root     # Database user
      POSTGRES_PASSWORD: 123pok! # User password
    ports:
      - "5432:5432"                   # Port mapping host:container
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist database data
    networks:
      - intranet

  frontend:
    container_name: frontend
    build: ./frontend/quiz-frontend/.
    restart: always
    ports:
      - "3000:3000"
    networks:
      - intranet

networks:
  intranet:
    driver: bridge


volumes:
  postgres_data:
